# Generated by Django 5.1.4 on 2024-12-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directory',
            new_name='director',
        ),
    ]
